# spring:
#   jpa:
#     generate-ddl : true
#     hibernate:
#       ddl-auto: update
#     properties :
#       hibernate:
#         show_sql: true
#         format_sql: true
#         dialect: org.hibernate.dialect.MariaDB103Dialect
#         storage_engine: innodb
#       connection:
#         characterEncoding: utf-8 
#         CharSet: utf-8 
#         useUnicode: true 
